---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname runtime-rundown
  namespace: runtime-rundown
spec:
  targetNamespace: runtime-rundown
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: "./runtime-rundown/app"
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: OCIRepository
    name: runtime-rundown-blueprint
    namespace: runtime-rundown
  wait: true
